name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install criterion
      run: sudo apt install -y libcriterion-dev
    - name: make
      run: make
    - name: make check
      run: make check
